wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.12.4
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.6.9
    start_time: 1655662886
    t:
      1:
      - 1
      - 5
      2:
      - 1
      - 5
      3:
      - 1
      - 17
      4: 3.6.9
      5: 0.12.4
      8:
      - 5
activation:
  desc: null
  value: None
anomaly_plot:
  desc: null
  value: true
batch_size:
  desc: null
  value: 128
checkpoint:
  desc: null
  value: best
clip:
  desc: null
  value: false
cuda:
  desc: null
  value: true
data_name:
  desc: null
  value: synthetic_1.csv
dropout:
  desc: null
  value: 0.1
early_stopping:
  desc: null
  value: true
epochs:
  desc: null
  value: 300
eval_plot:
  desc: null
  value: true
experiment_name:
  desc: null
  value: STOC_test
feature_size:
  desc: null
  value: 256
forecast:
  desc: null
  value: true
forecast_step:
  desc: null
  value: 1
gamma:
  desc: null
  value: 1.0
initrange:
  desc: null
  value: 0.1
lr:
  desc: null
  value: 0
make_plot:
  desc: null
  value: true
manualSeed:
  desc: null
  value: 42
max_norm:
  desc: null
  value: 1.0
min_epoch:
  desc: null
  value: 0
model:
  desc: null
  value: STOC
n_feature:
  desc: null
  value: 1
nhead:
  desc: null
  value: 8
normal:
  desc: null
  value: true
num_features:
  desc: null
  value: 1
num_layers:
  desc: null
  value: 1
patience:
  desc: null
  value: 300
pred_one:
  desc: null
  value: false
root_path:
  desc: null
  value: ../yahoo_S5/A2Benchmark/
save_last:
  desc: null
  value: false
shuffle:
  desc: null
  value: false
slide_size:
  desc: null
  value: 1
step_size:
  desc: null
  value: 5
test_ratio:
  desc: null
  value: 0.6
training:
  desc: null
  value: true
trend_learning:
  desc: null
  value: 'False'
valid_ratio:
  desc: null
  value: 0.1
version:
  desc: null
  value: 0
window_size:
  desc: null
  value: 48
